/// Flutter icons SmartKyat_POS
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SmartKyat_POS
///      fonts:
///       - asset: fonts/SmartKyat_POS.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SmartKyat_POS {
  SmartKyat_POS._();

  static const _kFontFam = 'SmartKyat_POS';
  static const String? _kFontPkg = null;

  static const IconData add_plus = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData progress = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
