/// Flutter icons SmartKyat_POS
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SmartKyat_POS
///      fonts:
///       - asset: fonts/SmartKyat_POS.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SmartKyat_POS {
  SmartKyat_POS._();

  static const _kFontFam = 'SmartKyat_POS';
  static const String? _kFontPkg = null;

  static const IconData add_plus = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData progress = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customer1 = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customer2 = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData merchant_1 = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData merchant = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData merge_arrow = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prodm = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prods1 = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prods2 = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData product = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData merge_arrow2 = IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
